# Role: para instalação completa do Carbon Black
# Data de criação: 05/09/2023
# Utiliza o template: N/A
# Criado por: William Lídio
---
- name: Criar diretório /mnt/carbon
  file:
    path: /mnt/carbon
    state: directory

- name: Baixar a versão mais atualizada do pacote
  get_url:
    url: http://192.168.50.224:8282/cb-psc-sensor-rhel-2.14.0.1321525.tar
    dest: /mnt/carbon/cb-psc-sensor-rhel-2.14.0.1321525.tar

- name: Extrair o pacote
  unarchive:
    src: /mnt/carbon/cb-psc-sensor-rhel-2.14.0.1321525.tar
    dest: /mnt/carbon
    remote_src: yes
    creates: /mnt/carbon/cb-psc-sensor-2.14.0-1321525.el9.x86_64.rpm

- name: Instalar o pacote RPM
  shell: sudo rpm -i cb-psc-sensor-2.14.0-1321525.el9.x86_64.rpm
  args:
    chdir: /mnt/carbon

- name: Executar o script bladesUnpack.sh
  shell: sh /mnt/carbon/blades/bladesUnpack.sh
  args:
    chdir: /mnt/carbon

- name: Indicar o serial
  command: /opt/carbonblack/psc/bin/cbagentd -d SX38GTIPWMSZYVQHM4I

- name: Habilitar e iniciar o serviço cbagentd
  systemd:
    name: cbagentd
    enabled: yes
    state: started
