---
- name: Login success or failure, logs to specified files.
  hosts: lab
  gather_facts: false
  become: true
  tasks:

  - name: Checking if rsyslog.conf has the necessary lines 1
    ignore_errors: true
    shell: grep ^"*.info;mail.none;authpriv.none;cron.none"  /etc/rsyslog.conf |awk '{print $2}'
    register: grep1_results

  - name: Checking if rsyslog.conf has the necessary lines 2
    ignore_errors: true
    shell: grep ^"authpriv.\*"  /etc/rsyslog.conf |awk '{print $2}'
    register: grep2_results

  - name: Including file "include-compliance.conf" in /etc/rsyslog.d/ directory if necessary 
    copy:
      src: /home/devops/ansible/house/Logging/include-csd-rsyslog.conf 
      dest: /etc/rsyslog.d/include-csd-rsyslog.conf
      mode: '0644'
      owner: root
      group: root
    when: ("/var/log/messages" not in grep1_results.stdout) or
          ("/var/log/secure" not in grep2_results.stdout)

  - name: Verifying copy file include-csd-rsyslog.conf
    stat: 
      path: /etc/rsyslog.d/include-csd-rsyslog.conf
    register: file_rsyslog
 
  - name: Restart Rsyslog service if necessary  
    service: 
      name: rsyslog
      state: restarted 
    when: file_rsyslog.stat.exists 
 
...
