# Role: para instalação completa do zabbix-agent2
# Data de criação: 05/09/2023
# Utiliza o template: oxt_cmd.conf e zabbix_agent2.conf
# Criado por: William Lídio
---
# Instalação do zabbix direto do repositório oficial
- name: Instalar o repositório Zabbix
  get_url:
    url: https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-release-6.4-1.el7.noarch.rpm
    dest: /tmp/zabbix-release.rpm

- name: Importar a chave GPG do repositório Zabbix
  shell: rpm --import https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591

- name: Instalar o pacote do repositório Zabbix
  yum:
    name: /tmp/zabbix-release.rpm
    state: present

- name: Instalar o pacote Zabbix Agent 2
  yum:
    name: "zabbix-agent2"
    state: present

- name: Instalar plugin Zabbix Agent 2
  yum:
    name: "zabbix-agent2-plugin-*"
    state: present

- name: Iniciar e habilitar o serviço Zabbix Agent 2
  systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes

- name: Remover o arquivo de instalação do repositório Zabbix
  file:
    path: /tmp/zabbix-release.rpm
    state: absent

- name: Iniciar o serviço Zabbix Agent 2
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: started

# Configuração do zabbix_agent2.conf com backup do original
- name: Verificar se o arquivo zabbix_agent2.conf original existe
  stat:
    path: /etc/zabbix/zabbix_agent2.conf
  register: zabbix_agent2_conf

- name: Fazer backup do arquivo zabbix_agent2.conf original
  copy:
    src: /etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf.backup
    remote_src: yes
  when: zabbix_agent2_conf.stat.exists

- name: Copiar arquivo de template zabbix_agent2.conf se o original existir
  copy:
    src: templates/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644' # adiciona as permissões -rw-r-r-
  when: zabbix_agent2_conf.stat.exists

- name: Adicionar hostname ao arquivo zabbix_agent2.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Hostname='
    line: 'Hostname={{ inventory_hostname }}'
  when: zabbix_agent2_conf.stat.exists

- name: Iniciar o serviço Zabbix Agent 2
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: started

# Adiciona o arquivo oxt_cmd.conf no /etc/zabbix/zabbix_agent2.d/
- name: Verificar se o arquivo oxt_cmd.conf original existe
  stat:
    path: /etc/zabbix/zabbix_agent2.d/oxt_cmd.conf
  register: oxt_cmd_conf

- name: Fazer backup do arquivo oxt_cmd_conf original
  copy:
    src: /etc/zabbix/zabbix_agent2.d/oxt_cmd.conf
    dest: /etc/zabbix/zabbix_agent2.d/oxt_cmd.conf.backup
    remote_src: yes
  when: oxt_cmd_conf.stat.exists

- name: Copiar arquivo de template oxt_cmd.conf se o original existir
  copy:
    src: templates/oxt_cmd.conf
    dest: /etc/zabbix/zabbix_agent2.d/oxt_cmd.conf
    owner: root
    group: root
    mode: '0644' # adiciona as permissões -rw-r-r-
  # when: oxt_cmd_conf.stat.exists
