---
- name: Template
  hosts: lab
  gather_facts: true
  become: true
  tasks:

  - name: Block of tasks for CentOS and Red Hat Linux
    block:



    - name: Creating ansible log HCFindings 
      shell: echo "$(date +%b" "%d" "%T) - Findings -> SystemSettings-IZ.X.yml - {{ inventory_hostname }} - XXXXXX TEXT OUTPUT XXXXX " >> /var/log/HCFindings.log
      delegate_to: localhost
      when:
  

    when: ansible_facts['distribution'] == 'CentOS' or
          ansible_facts['distribution'] == 'RedHat'
          
...