# Role: para atualização do hostname usando o NetworkManager
# Data de criação: 05/09/2023
# Utiliza o template: N/A
# Criado por: William Lídio
---
- name: Definir novo hostname no NetworkManager
  command: nmcli general hostname {{ inventory_hostname }}
  changed_when: true
  register: resultado_hostname

- name: Hostnamectl para instalar o hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}.linux.ssa.corp
  when: resultado_hostname.changed

- name: Adicionar novo hostname ao /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] if hostvars[inventory_hostname]['ansible_eth1'] is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ inventory_hostname }}.linux.ssa.corp {{ inventory_hostname }} {{ alias | default('') }}"
    state: present
    backup: yes

- name: Reiniciar o serviço de rede
  service:
    name: NetworkManager
    state: restarted
  when: resultado_hostname.changed
...