# Role: para instalação completa do Graylog Sidecar, Rsyslog e Filebeat
# Data de criação: 05/09/2023
# Utiliza o template: N/A
# Criado por: William Lídio
---
# Instalação do Graylog Sidecar
- name: Download do Graylog Sidecar RPM
  get_url:
    url: http://192.168.50.224:8282/graylog-sidecar-1.0.2-1.x86_64.rpm
    dest: /tmp/graylog-sidecar.rpm

- name: Instalar Graylog Sidecar RPM
  yum:
    name: /tmp/graylog-sidecar.rpm
    state: present
    disable_gpg_check: yes

- name: Configurar Graylog Sidecar
  lineinfile:
    path: /etc/graylog/sidecar/sidecar.yml
    line: "{{ item }}"
  loop:
    - 'server_url: "http://192.168.50.17:9000/api/"'
    - 'server_api_token: "ujj783bceo5vuatrq3fugm2ikkl72019fks9j4mrq6fe64tlbd3"'
    - 'tls_skip_verify: true'

- name: Reiniciar Graylog Sidecar
  systemd:
    name: graylog-sidecar
    enabled: yes
    state: restarted

- name: Instalar rsyslog
  yum:
    name: rsyslog
    state: present

# Instalação do Filebeat
- name: Baixar o instalador Filebeat
  get_url:
    url: "http://192.168.50.224:8282/filebeat-6.8.1-x86_64.rpm"
    dest: /tmp/filebeat-6.8.1-x86_64.rpm

- name: Instalar o pacote Filebeat usando yum
  yum:
    name: /tmp/filebeat-6.8.1-x86_64.rpm
    state: present
    disable_gpg_check: yes

- name: Reiniciar Filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted

# Instalação do Rsyslog
- name: Verificar se o arquivo /etc/rsyslog.conf original existe
  stat:
    path: /etc/rsyslog.conf
  register: rsyslog_conf

- name: Configurar Rsyslog para encaminhar logs para 10.4.0.86
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @10.4.0.86:1514;RSYSLOG_SyslogProtocol23Format"
    state: present
  when: rsyslog_conf.stat.exists

- name: Adicionar encaminhamento para 192.168.50.17
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @192.168.50.17:1514;RSYSLOG_SyslogProtocol23Format"
    state: present
  when: rsyslog_conf.stat.exists

- name: Reiniciar servico do rsyslog
  systemd:
    name: rsyslog
    state: restarted
