---
- name: Configurar permissões e agendamento do script
  hosts: apps, dbs
  become: yes

  tasks:
    - name: Verificar se o arquivo permissoes.sh original existe
      stat:
        path: /etc/zabbix/permissoes.sh
      register: permissoes_sh

    - name: Fazer backup do arquivo permissoes.sh original
      copy:
        src: /etc/zabbix/permissoes.sh
        dest: /etc/zabbix/permissoes.sh.backup
        remote_src: yes # para ser executado no host remoto
      when: permissoes_sh.stat.exists

    - name: Copiar permissoes.sh para o servidor
      copy:
        src: templates/permissoes.sh
        dest: /etc/zabbix/permissoes.sh
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Adicionar entrada no crontab para executar o script a cada 30 minutos
      cron:
        name: Executar permissoes.sh a cada 30 minutos
        user: root
        minute: '*/30'
        job: /etc/zabbix/permissoes.sh
