---
- name: The second field of "/etc/passwd" may not be null.
  hosts: lab
  gather_facts: false
  become: true
  tasks:

  - name: Verifing "/etc/passwd" file 
    shell: cat /etc/passwd
    register: passwd_results

  - name: Creating variable of 2 field is empty in /etc/passwd
    set_fact:
      passwd_field_is_empty: true
    with_items: "{{ passwd_results.stdout_lines }}"
    when: item.split(':')[1] == ''

  - name: Backup /etc/passwd file 
    shell: /usr/bin/cp -p /etc/passwd /etc/passwd_bkp_csd_$(date +%F-%T)
    ignore_errors: true
    when: passwd_field_is_empty == true

  - name: Creating ansible log with user information and what Playbook its running.
    shell: echo "PasswordRequirements-IZ.1.1.2.2.yml - {{ inventory_hostname }} - user {{ item.split(':')[0] }} is out of compliance and was locked out due to password field being empty in "/etc/passwd"." >> /var/log/HCresults.log
    delegate_to: 127.0.0.1
    with_items: "{{ passwd_results.stdout_lines }}"
    when: 
      - item.split(':')[1] == ''
    
  - name: Locking out and setting nologin shell to accounts that are out of compliance.
    shell: "usermod -s $(which nologin) -L {{ item.split(':')[0] }}"
    with_items: "{{ passwd_results.stdout_lines }}"
    when: 
      - item.split(':')[1] == ''
...