# Playbook to verify Password Requirements - checking items per session
# created: Nov/2022
# Rafael Conte Monteiro

---
- name: Password Requirements - checking items per session
  gather_facts: false
  become: true
  hosts: localhost
  
  tasks:
    # checking item PASS_MAX_DAYS on /etc/login.defs
  - name: acme - Section 1.1 "PASS_MAX_DAYS"
    ansible.builtin.shell: grep "PASS_MAX_DAYS 90" /etc/login.defs
    register: pass_max_days_contents

  - name: Checking "PASS_MAX_DAYS" on /etc/login.defs
    ansible.builtin.shell: echo "PASS_MAX_DAYS = 90 --- OK"
    when: pass_max_days_contents.stdout.find('PASS_MAX_DAYS 90') != 1    

  - name: Checking Field 5 of "/etc/shadow" value 90
    ansible.builtin.shell: "awk -F: '{print $5}' /etc/shadow"





...
