# Playbook to verify reuse of last 8 passwords with pam_unix.so module
# created: Nov/2022
# Rafael Conte Monteiro

---
- name: Prevent reuse of last 8 passwords with pam_unix.so module
  hosts: lab
  gather_facts: true
  become: true
  
  tasks:

  - name: Creating a block tasks for Red Hat Linux
    block:

    - name: Reading /etc/pam.d/system-auth file
      shell: grep -i pam_unix.so /etc/pam.d/system-auth | grep -i remember=8
      ignore_errors: true 
      register: system_auth

    - name: Reading /etc/pam.d/password-auth file
      shell: grep -i pam_unix.so /etc/pam.d/password-auth | grep -i remember=8
      ignore_errors: true
      register: password_auth

    - name: Printing system_auth results before the changes 
      debug:
        msg: "{{ system_auth.stdout }}"

    - name: Printing password_auth results before the changes 
      debug:
        msg: "{{ password_auth.stdout }}"

    - name: Creating a backup of system-auth file 
      shell: /bin/cp -p /etc/pam.d/system-auth /etc/pam.d/system-auth_bkp_csd_$(date +%F-%T)
      when: '"remember=8" not in system_auth.stdout' 

    - name: Creating a backup password-auth file
      shell: /bin/cp -p /etc/pam.d/password-auth /etc/pam.d/password-auth_bkp_csd_$(date +%F-%T)
      when: '"remember=8" not in password_auth.stdout'

    - name: Adding the correct pam_unix.so line to the system-auth file
      lineinfile:
        path: /etc/pam.d/system-auth
        line: 'password    sufficient                                   pam_unix.so sha512 shadow use_authtok remember=8'
        regexp: '^(password\s+sufficient\s+pam_unix\.so*)'
        insertafter: '^password'
        state: present
      when: '"remember=8" not in system_auth.stdout' 

    - name: Adding the correct pam_unix.so line to the password-auth file
      lineinfile:
        path: /etc/pam.d/password-auth
        line: 'password    sufficient                                   pam_unix.so sha512 shadow use_authtok remember=8'
        regexp: '^(password\s+sufficient\s+pam_unix\.so*)'
        insertafter: '^password'
        state: present
      when: '"remember=8" not in password_auth.stdout' 

    - name: Reading again /etc/pam.d/system-auth file
      shell: grep -i pam_unix.so /etc/pam.d/system-auth | grep -i remember=8
      ignore_errors: true 
      register: system_auth_new

    - name: Reading again /etc/pam.d/password-auth file
      shell: grep pam_unix.so /etc/pam.d/password-auth | grep -i remember=8
      ignore_errors: true
      register: password_auth_new

    - name: Printing system_auth_new results after the changes 
      debug:
        msg: "{{ system_auth_new.stdout }}"

    - name: Printing password_auth_new results after the changes 
      debug:
        msg: "{{ password_auth_new.stdout }}"

    when: ansible_facts['distribution'] == 'RedHat'
...