# Playbook to verify setting the per-userid minimum number of days = "1" in /etc/shadow
# created: Nov/2022
# Rafael Conte Monteiro

---
- name: Setting the per-userid minimum number of days = "1" in /etc/shadow
  hosts: lab
  gather_facts: false
  become: true
  tasks:

  - name: Verify file /etc/shadow
    shell: cat /etc/shadow
    register: shadow_content

  - name: Checking compliance
    set_fact:
      not_equal_to_1: true
    with_items: "{{ shadow_content.stdout_lines }}"
    when:
      - item.split(':')[1] != '*'
      - item.split(':')[1] != '!'
      - item.split(':')[1] != '!!'
      - item.split(':')[1] != 'x'
      - item.split(':')[3]| int != 1

  - name: Backup /etc/shadow file if the value is not correct
    shell: /usr/bin/cp -p /etc/shadow /etc/shadow_bkp_csd_$(date +%F-%T)
    when: not_equal_to_1 == true

  - name: Changing minimum password age field 4
    shell: "chage -m 1 {{ item.split(':')[0] }}"
    with_items: "{{ shadow_content.stdout_lines }}"
    when:
      - item.split(':')[1] != '*'
      - item.split(':')[1] != '!'
      - item.split(':')[1] != '!!'
      - item.split(':')[1] != 'x'
      - item.split(':')[3] | int != 1

  - name: Creating ansible log with user information.
    shell: echo "{{ inventory_hostname }} - user {{ item.split(':')[0] }} is out of compliance and "minimum number of days between password change" value is being changed to meet password security requirements." >> /var/log/HCresults.log
    delegate_to: 127.0.0.1
    with_items: "{{ shadow_content.stdout_lines }}"
    when:
      - item.split(':')[1] != '*'
      - item.split(':')[1] != '!'
      - item.split(':')[1] != '!!'
      - item.split(':')[1] != 'x'
      - item.split(':')[3]| int != 1
...
