# Playbook to verify password age value to 90 in /etc/shadow
# created: Nov/2022
# Rafael Conte Monteiro

---
- name: Setting password age value to 90 in /etc/shadow
  hosts: lab
  gather_facts: false
  become: true
  tasks:

  - name: Seting vars
    command: cat /etc/shadow
    register: shadow_content

  - name: Checking compliance 
    set_fact: 
      is_above_90: true  
    with_items: "{{ shadow_content.stdout_lines }}"
    register: accounts
    when: 
      - item.split(':')[1] != '*'   
      - item.split(':')[1] != '!' 
      - item.split(':')[1] != '!!'
      - item.split(':')[1] != 'x'        
      - item.split(':')[4]| int > 90 

  - name: Backup original file /etc/shadow
    shell: /bin/cp -p /etc/shadow /etc/shadow_bkp_csd_$(date +%F-%T)
    ignore_errors: 
    when: is_above_90 == true 

  - name: Execute max_pass_age.sh shellscript
    shell: "chage -M 90 {{ item.split(':')[0] }}" 
    with_items: "{{ shadow_content.stdout_lines }}"
    register: accounts
    when: 
      - item.split(':')[1] != '*'   
      - item.split(':')[1] != '!' 
      - item.split(':')[1] != '!!'
      - item.split(':')[1] != 'x'        
      - item.split(':')[4]| int > 90
 
  - name: Creating ansible log with user information.
    shell: echo "{{ inventory_hostname }} - user {{ item.split(':')[0] }} is out of compliance and "maximum number of days between password change" value is being changed to meet password security requirements." >> /var/log/HCresults.log
    delegate_to: 127.0.0.1
    with_items: "{{ shadow_content.stdout_lines }}"
    when:
      - item.split(':')[1] != '*'
      - item.split(':')[1] != '!'
      - item.split(':')[1] != '!!'
      - item.split(':')[1] != 'x'
      - item.split(':')[4]| int > 90
...      
