# Role: para desinstalar o easy inventory
# Data de criação: 12/09/2023
# Utiliza o template: N/A
# Criado por: Rafael
---
- name: Executar múltiplos comandos
  shell: |
    systemctl stop easy2l
    systemctl disable easy2l
    cd /opt/
    rm -rfv easy/
