# Role: para remoção completa do IPA Client 
# Data de criação: 11/09/2023
# Utiliza o template: N/A
# Versão 0.1
# Criado por: William Lídio 
---
- name: Remover os pacotes do ipa-client
  dnf:
    name: "{{ item }}"
    state: absent
  loop:
    - ipa-client
    - ipa-client-common
    - ipa-common
    - ipa-selinux
    - sssd-ipa
