# Role: para adicionar banner + history + motdyn
# Data de criação: 04/09/2023
# Utiliza o template: motdyn.sh e bannersonepar.sh
# Criado por: William Lídio

---
# Adiciona as configurações do motdyn
- name: Fazer backup do arquivo profile original
  copy:
    src: /etc/profile
    dest: /etc/profile.backup
    remote_src: yes

- name: Copiar arquivo de template motdyn.sh
  template:
    src: ../../../templates/motdyn.sh
    dest: /usr/local/bin/motdyn.sh
    owner: root
    group: root
    mode: '755' # adiciona as permissões -rwxr-xr-x

- name: Adicionar a linha no /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: "^/usr/local/bin/motdyn.sh$"
    line: "/usr/local/bin/motdyn.sh"

# Adiciona as configurações do bashrc do root e recarrega o arquivo
- name: Verificar se o bloco já existe no .bashrc
  command: cat /root/.bashrc
  register: bashrc_content

- name: Configurar .bashrc do root
  lineinfile:
    path: /root/.bashrc
    line: "{{ item }}"
    insertafter: EOF
    regexp: "{{ item }}"
  loop:
    - "# Configuração do bashrc"
    - "HISTFILESIZE=10000"
    - "HISTSIZE=10000"
    - "HISTCONTROL=ignorespace"
    - "HISTTIMEFORMAT='%d/%m/%y %T '"
  when: "'# Configuração do bashrc' not in bashrc_content.stdout_lines"

- name: Recarregar .bashrc
  shell: source /root/.bashrc

# Adiciona configurações do banner sonepar
- name: Fazer backup do arquivo sshd_config original
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    remote_src: yes

- name: Copiar arquivo de template bannersonepar.net
  template:
    src: ../../../templates/bannersonepar.net
    dest: /etc/bannersonepar.net
    owner: root
    group: root
    mode: '0644' # adiciona as permissões -rw-r-r-

- name: Adicionar a linha no /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Banner /etc/bannersonepar.net$"
    line: Banner /etc/bannersonepar.net
